// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7t0mfxzYky1cQ7O0ZJ17ZyOFY2NhjyEs',
    appId: '1:222390355428:web:7e1503ffbcbd1e585e33f1',
    messagingSenderId: '222390355428',
    projectId: 'quiz-app-39970',
    authDomain: 'quiz-app-39970.firebaseapp.com',
    storageBucket: 'quiz-app-39970.firebasestorage.app',
    measurementId: 'G-7QML42PNKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJI2A0X-0AQ9KH638p6i2QarjnzSH9MyQ',
    appId: '1:222390355428:android:f023dfa8d07a902d5e33f1',
    messagingSenderId: '222390355428',
    projectId: 'quiz-app-39970',
    storageBucket: 'quiz-app-39970.firebasestorage.app',
  );
}
